name: Split

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

env:
  GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

jobs:
  packages_split:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        package:
          - local_path: 'core'
            split_repository: 'antares'
          - local_path: 'validation'
            split_repository: 'antares-validation'
          - local_path: 'container'
            split_repository: 'antares-container'
          - local_path: 'router'
            split_repository: 'antares-router'
          - local_path: 'bridges/monolog'
            split_repository: 'antares-monolog-bridge'
          - local_path: 'bridges/eloquent'
            split_repository: 'antares-eloquent-bridge'

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: danharrin/monorepo-split-github-action@v2.4.0
        with:
          package_directory: 'packages/${{ matrix.package.local_path }}'
          repository_organization: 'johnlesis'
          repository_name: '${{ matrix.package.split_repository }}'
          branch: 'main'
          user_name: 'johnlesis'
          user_email: 'johnlesis91@gmail.com'