name: Split

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  split:
    runs-on: ubuntu-latest
    steps:
      - uses: symplify/github-action-monorepo-split@main
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          package_directory: 'packages/core'
          repository_organization: 'johnlesis'
          repository_name: 'antares'
          branch: 'main'

      - uses: symplify/github-action-monorepo-split@main
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          package_directory: 'packages/validation'
          repository_organization: 'johnlesis'
          repository_name: 'antares-validation'
          branch: 'main'

      - uses: symplify/github-action-monorepo-split@main
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          package_directory: 'packages/container'
          repository_organization: 'johnlesis'
          repository_name: 'antares-container'
          branch: 'main'

      - uses: symplify/github-action-monorepo-split@main
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          package_directory: 'packages/router'
          repository_organization: 'johnlesis'
          repository_name: 'antares-router'
          branch: 'main'

      - uses: symplify/github-action-monorepo-split@main
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          package_directory: 'packages/bridges/monolog'
          repository_organization: 'johnlesis'
          repository_name: 'antares-monolog-bridge'
          branch: 'main'

      - uses: symplify/github-action-monorepo-split@main
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          package_directory: 'packages/bridges/eloquent'
          repository_organization: 'johnlesis'
          repository_name: 'antares-eloquent-bridge'
          branch: 'main'